Add support for ubuntu 20.04
crigroup/openrave-installation pull request #16
Opened 2020-08-14 04:03 UTC by leonardoedgar

2020-08-14 09:30 UTC, nicholasadr commented
Cool! I notice that this commit upgrades the script compatibility to newer versions of Ubuntu and OpenRAVE (`production` branch I assume?). Out of curiosity, which changes are intended for the Ubuntu distro upgrade and which are for upgrading the OpenRAVE version? Asking in case I want to do different installation combination, e.g. Ubuntu 18 + OpenRAVE 0.53

2020-08-14 09:36 UTC, leonardoedgar commented
> Cool! I notice that this commit upgrades the script compatibility to newer versions of Ubuntu and OpenRAVE (`production` branch I assume?). Out of curiosity, which changes are intended for the Ubuntu distro upgrade and which are for upgrading the OpenRAVE version? Asking in case I want to do different installation combination, e.g. Ubuntu 18 + OpenRAVE 0.53

Yes, it is one of the latest commit from the production branch (just committed this week). For now the script only allows the following configs:
- Ubuntu 14.04 with OpenRAVE 0.9
- Ubuntu 16.04 with OpenRAVE 0.9
- Ubuntu 18.04 with OpenRAVE 0.9
- Ubuntu 20.04 with OpenRAVE 0.53
There is only 1 OpenRAVE version for each OS, so the user will not have any options to select which OpenRAVE version to install.

2020-08-24 00:13 UTC, mstallone requested changes
Tried this feature branch on a fresh install of Ubuntu 20.04, ran into a few QOL errors with the dependency script; otherwise, seems like it installs openrave v0.53.1 correctly.

Appreciate the work with maintaining and updating this!

2020-08-24 00:13 UTC, mstallone commented on install-dependencies.sh
> +  curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
On a fresh install of Ubuntu:20.04, curl is not installed so pip2 fails to install.

2020-08-24 00:13 UTC, mstallone commented on install-dependencies.sh
> +  cmake .. && make -j `nproc` && make install
Installing rapidjson and pybind11 fails when running without permissions. Might suggest changing to `sudo make install` for both like osg, fcl, and openrave script files.

2020-08-24 00:13 UTC, mstallone commented on install-dependencies.sh
> +    && make install
See rapidjson comment
`sudo make install`

2020-08-24 15:16 UTC, nicholasadr commented
I haven't had the time to look into this but given the recent review it seems that it's good to go. Let me know if you want me (or anyone else) to merge it @leonardoedgar ?

2020-08-24 15:19 UTC, leonardoedgar commented
> I haven't had the time to look into this but given the recent review it seems that it's good to go. Let me know if you want me (or anyone else) to merge it @leonardoedgar ?

I think we can merge this to master already.

2020-08-24 15:21 UTC, nicholasadr commented
Thanks @leonardoedgar @mstallone, i'll merge this

2020-08-24 15:23 UTC, merged

2020-08-24 15:23 UTC, nicholasadr commented
Thanks @leonardoedgar @mstallone, i'll merge this